name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: install conan
      run: pip3 install conan
    - name: create new conan profile
      run: conan profile new default --detect
    - name: update profile to c++11
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: add conan remote
      run: conan remote add conan-cpp https://api.bintray.com/conan/squawkcpp/conan-cpp
    - name: install conan dependencies
      run: conan install "$GITHUB_WORKSPACE" --install-folder "$GITHUB_WORKSPACE/build"
    - name: build AOC2019
      run: conan build "$GITHUB_WORKSPACE" --build-folder "$GITHUB_WORKSPACE/build"
    - name: run tests
      run: |
        cd "$GITHUB_WORKSPACE/build"
        ctest -T test 
