name: CI

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Run build-tools build command
        uses: buildtool/build-action@v1
        with:
          dockerfile: .devcontainer/Dockerfile
          docker-build-args: '-skiplogin'
